### ISSUE TITLE
Running Twinkieset locally

### ISSUE THREAD

**Issue by dakshshah96** [karenling/Twinkieset#4]
Hey @karenling,

I've gotten till the step where I installed all the dependencies for this project successfully using `bundle install`. 

However, I'm new to Ruby and couldn't figure out how to really start the server so I can run Twinkieset locally. I need some help and it'd be great if you could help me regarding the same.

Thanks!

**Comment by jackeown** [comment]
ditto.

**Comment by jackeown** [comment]
I eventually figured it out!  
I had to fix problems with "rake":
```
sudo rm /usr/share/rubygems-integration/all/specifications/rake-10.5.0.gemspec
bundle install
```

And then I had to make my user a postgresql user (and make it a superuser):
```
sudo -u postgres psql
CREATE USER davide WITH PASSWORD 'jw8s0F4';
ALTER USER davide WITH SUPERUSER;
```

Then I ran:
```
rake db:setup
```

and finally!
```
rails s
```
(which made a server running on localhost:3000)
